%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\admin\Desktop\taskexcel111.xlsx
%    Worksheet: Soybeans
%
% Auto-generated by MATLAB on 11-Feb-2019 00:26:59

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Soybeans";
opts.DataRange = "A2:I121";

% Specify column names and types
opts.VariableNames = ["Product", "ProductCode", "MonthCode", "MonthCodeLong", "LocalProductCode", "TradingExchange", "IVModel", "IVSurface", "Futures"];
opts.VariableTypes = ["categorical", "categorical", "string", "string", "double", "categorical", "string", "string", "string"];
opts = setvaropts(opts, [3, 4, 7, 8, 9], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 6, 7, 8, 9], "EmptyFieldRule", "auto");

% Import the data
taskexcel1 = readtable("C:\Users\admin\Desktop\taskexcel111.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts